### ISSUE TITLE
ModuleNotFoundError: No module named 'alfworld' 

### ISSUE THREAD

**Issue by uglyghost** [noahshinn/reflexion#22]
C:\Users\20834\anaconda3\envs\reflexion\python.exe F:\reflexion\alfworld_runs\main.py --num_trials 10 --num_envs 134 --run_name reflexion_run_logs --use_memory --model gpt-3.5-turbo 
Traceback (most recent call last):
  File "F:\reflexion\alfworld_runs\main.py", line 5, in <module>
    from alfworld_trial import run_trial
  File "F:\reflexion\alfworld_runs\alfworld_trial.py", line 9, in <module>
    import alfworld
ModuleNotFoundError: No module named 'alfworld'

**Comment by bf-yang** [comment]
Same problem. I have tried to install alfworld package, but it only supports python3.6 and torchvision0.4.0.
I am wondering how to integrate alfworld into this project in one environment.
